name: CI

on:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    permissions:
      checks: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install  --no-root --sync

      - name: Run migrations
        run: poetry run python manage.py migrate --noinput

      - name: Run pytest with coverage
        continue-on-error: true
        run: |
          poetry run coverage run -m pytest --junit-xml=pytest.xml
          poetry run coverage xml -o coverage.xml



      - name: Publish coverage results
        if: always()
        uses: aGallea/tests-coverage-report@v1
        with:
          cobertura-path:
            coverage.xml
          junit-path:
            pytest.xml
          show-diffcover: 'true'

      - name: Get latest PR number
        id: get-pr-number
        run: |
          PR_JSON=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls?state=open&sort=created&direction=desc&per_page=1")
          PR_NUMBER=$(echo "$PR_JSON" | jq -r '.[0].number')
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV

      - name: Review agent
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
        run: poetry run python agent.py $GITHUB_TOKEN $REPOSITORY $PR_NUMBER $OPENAI_API_KEY $OPENAI_BASE_URL

