name: Test OpenAI with LlamaIndex

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  llamaindex-openai-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install llama-index openai

    - name: Run test script
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}  # optional
        OPENAI_MODEL: ${{ secrets.OPENAI_MODEL }}
      run: python test_openai.py
